development:
  adapter: postgresql
  database: ng-cors-api-development
  host: localhost
  pool: 5
  timeout: 5000
  host_names:
    - "localhost"
test:
  adapter: postgresql
  database: ng-cors-api-test
  host: localhost
  pool: 5
  timeout: 5000
  host_names:
    - "localhost"
