(set-default-font "Source Code Pro:size=29")
(global-set-key (kbd "s-<right>") 'bufshow-next)
(global-set-key (kbd "s-<left>") 'bufshow-prev)
(global-set-key (kbd "s-<down>") 'writeroom-mode)
(setq writeroom-width 0.5)
(writeroom-mode)
(bufshow-start
  [("e1.rb")
   ("e2.rb")
   ("e3.rb")
   ("e4.rb")
   ("e5.rb")
   ("e6.rb")
   ("e7.rb")
   ("e8.rb")
   ("e9.rb")
   ("e10.rb")])
